spring:
  datasource:
    url: jdbc:mysql://database-1.ct2kw6s88itk.ap-northeast-2.rds.amazonaws.com:3306/Networker  
    username: root
    password: testdbpw
#   driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: yuntyu01
    password: "앱 비밀번호"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#pull내용 유지
  thymeleaf:
    prefix: classpath:/static/views
    suffix: .html
    cache: false  
    mode: html
    encoding: UTF-8
    servlet:
      content-type: text/html